// <auto-generated />
using Final.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Final.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250621183634_InitialCreateWithSeedData")]
    partial class InitialCreateWithSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Final.Domain.Entities.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "CPU (Vi xử lý)"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "GPU (Card đồ họa)"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "RAM (Bộ nhớ trong)"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "SSD (Ổ cứng thể rắn)"
                        },
                        new
                        {
                            Id = 5L,
                            Name = "PSU (Nguồn máy tính)"
                        });
                });

            modelBuilder.Entity("Final.Domain.Entities.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CategoryId = 1L,
                            Name = "Intel Core i9-14900K",
                            Price = 15500000m
                        },
                        new
                        {
                            Id = 2L,
                            CategoryId = 1L,
                            Name = "Intel Core i7-14700K",
                            Price = 11200000m
                        },
                        new
                        {
                            Id = 3L,
                            CategoryId = 1L,
                            Name = "AMD Ryzen 9 7950X3D",
                            Price = 14800000m
                        },
                        new
                        {
                            Id = 4L,
                            CategoryId = 1L,
                            Name = "AMD Ryzen 7 7800X3D",
                            Price = 9800000m
                        },
                        new
                        {
                            Id = 5L,
                            CategoryId = 2L,
                            Name = "NVIDIA GeForce RTX 4090",
                            Price = 45000000m
                        },
                        new
                        {
                            Id = 6L,
                            CategoryId = 2L,
                            Name = "NVIDIA GeForce RTX 4080 Super",
                            Price = 31000000m
                        },
                        new
                        {
                            Id = 7L,
                            CategoryId = 2L,
                            Name = "AMD Radeon RX 7900 XTX",
                            Price = 28500000m
                        },
                        new
                        {
                            Id = 8L,
                            CategoryId = 2L,
                            Name = "AMD Radeon RX 7800 XT",
                            Price = 15000000m
                        },
                        new
                        {
                            Id = 9L,
                            CategoryId = 3L,
                            Name = "Corsair Vengeance DDR5 32GB (2x16GB) 6000MHz",
                            Price = 3200000m
                        },
                        new
                        {
                            Id = 10L,
                            CategoryId = 3L,
                            Name = "G.Skill Trident Z5 RGB DDR5 32GB (2x16GB) 6400MHz",
                            Price = 3800000m
                        },
                        new
                        {
                            Id = 11L,
                            CategoryId = 3L,
                            Name = "Kingston Fury Beast DDR5 16GB 5200MHz",
                            Price = 1500000m
                        },
                        new
                        {
                            Id = 12L,
                            CategoryId = 3L,
                            Name = "Crucial Pro DDR5 16GB 5600MHz",
                            Price = 1450000m
                        },
                        new
                        {
                            Id = 13L,
                            CategoryId = 4L,
                            Name = "Samsung 990 Pro NVMe M.2 SSD 2TB",
                            Price = 4500000m
                        },
                        new
                        {
                            Id = 14L,
                            CategoryId = 4L,
                            Name = "WD Black SN850X NVMe M.2 SSD 2TB",
                            Price = 4200000m
                        },
                        new
                        {
                            Id = 15L,
                            CategoryId = 4L,
                            Name = "Crucial P5 Plus NVMe M.2 SSD 1TB",
                            Price = 2100000m
                        },
                        new
                        {
                            Id = 16L,
                            CategoryId = 4L,
                            Name = "Kingston KC3000 NVMe M.2 SSD 1TB",
                            Price = 2300000m
                        },
                        new
                        {
                            Id = 17L,
                            CategoryId = 5L,
                            Name = "Corsair RM1000e 1000W 80+ Gold",
                            Price = 4100000m
                        },
                        new
                        {
                            Id = 18L,
                            CategoryId = 5L,
                            Name = "Seasonic FOCUS Plus Gold 850W",
                            Price = 3400000m
                        },
                        new
                        {
                            Id = 19L,
                            CategoryId = 5L,
                            Name = "Cooler Master MWE Gold 750 V2",
                            Price = 2500000m
                        },
                        new
                        {
                            Id = 20L,
                            CategoryId = 5L,
                            Name = "MSI MPG A850G PCIE5 850W",
                            Price = 3600000m
                        });
                });

            modelBuilder.Entity("Final.Domain.Entities.Product", b =>
                {
                    b.HasOne("Final.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Final.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
